type t =
| ACC0
| ACC1
| ACC2
| ACC3
| ACC4
| ACC5
| ACC6
| ACC7
| ACC
| PUSH
| PUSHACC1
| PUSHACC2
| PUSHACC3
| PUSHACC4
| PUSHACC5
| PUSHACC6
| PUSHACC7
| PUSHACC
| POP
| ASSIGN
| ENVACC1
| ENVACC2
| ENVACC3
| ENVACC4
| ENVACC
| PUSHENVACC1
| PUSHENVACC2
| PUSHENVACC3
| PUSHENVACC4
| PUSHENVACC
| PUSH_RETADDR_1B
| PUSH_RETADDR_2B
| PUSH_RETADDR_4B
| APPLY
| APPLY1
| APPLY2
| APPLY3
| APPTERM
| APPTERM1
| APPTERM2
| APPTERM3
| RETURN
| RESTART
| GRAB
| CLOSURE_1B
| CLOSURE_2B
| CLOSURE_4B
| CLOSUREREC_1B
| CLOSUREREC_2B
| CLOSUREREC_4B
| OFFSETCLOSUREM2
| OFFSETCLOSURE0
| OFFSETCLOSURE2
| OFFSETCLOSURE
| PUSHOFFSETCLOSUREM2
| PUSHOFFSETCLOSURE0
| PUSHOFFSETCLOSURE2
| PUSHOFFSETCLOSURE
| GETRAMGLOBAL_1B
| GETFLASHGLOBAL_1B
| GETRAMGLOBAL_2B
| GETFLASHGLOBAL_2B
| PUSHGETRAMGLOBAL_1B
| PUSHGETFLASHGLOBAL_1B
| PUSHGETRAMGLOBAL_2B
| PUSHGETFLASHGLOBAL_2B
| GETRAMGLOBALFIELD_1B
| GETFLASHGLOBALFIELD_1B
| GETRAMGLOBALFIELD_2B
| GETFLASHGLOBALFIELD_2B
| PUSHGETRAMGLOBALFIELD_1B
| PUSHGETFLASHGLOBALFIELD_1B
| PUSHGETRAMGLOBALFIELD_2B
| PUSHGETFLASHGLOBALFIELD_2B
| SETRAMGLOBAL_1B
| SETRAMGLOBAL_2B
| ATOM0
| PUSHATOM0
| MAKEBLOCK_1B
| MAKEBLOCK_2B
| MAKEBLOCK1
| MAKEBLOCK2
| MAKEBLOCK3
| GETFIELD0
| GETFIELD1
| GETFIELD2
| GETFIELD3
| GETFIELD
| SETFIELD0
| SETFIELD1
| SETFIELD2
| SETFIELD3
| SETFIELD
| VECTLENGTH
| GETVECTITEM
| SETVECTITEM
| GETBYTESCHAR
| SETBYTESCHAR
| BRANCH_1B
| BRANCH_2B
| BRANCH_4B
| BRANCHIF_1B
| BRANCHIF_2B
| BRANCHIF_4B
| BRANCHIFNOT_1B
| BRANCHIFNOT_2B
| BRANCHIFNOT_4B
| SWITCH_1B
| SWITCH_2B
| SWITCH_4B
| BOOLNOT
| PUSHTRAP_1B
| PUSHTRAP_2B
| PUSHTRAP_4B
| POPTRAP
| RAISE
| CHECK_SIGNALS
| C_CALL1
| C_CALL2
| C_CALL3
| C_CALL4
| C_CALL5
| C_CALLN
| CONST0
| CONST1
| CONST2
| CONST3
| CONSTINT_1B
| CONSTINT_2B
| CONSTINT_4B
| PUSHCONST0
| PUSHCONST1
| PUSHCONST2
| PUSHCONST3
| PUSHCONSTINT_1B
| PUSHCONSTINT_2B
| PUSHCONSTINT_4B
| CONSTFLOAT
| PUSHCONSTFLOAT
| NEGINT
| ADDINT
| SUBINT
| MULINT
| DIVINT
| MODINT
| ANDINT
| ORINT
| XORINT
| LSLINT
| LSRINT
| ASRINT
| EQ
| NEQ
| LTINT
| LEINT
| GTINT
| GEINT
| OFFSETINT_1B
| OFFSETINT_2B
| OFFSETINT_4B
| OFFSETREF_1B
| OFFSETREF_2B
| OFFSETREF_4B
| ISINT
| GETMETHOD
| BEQ_1B
| BEQ_2B
| BEQ_4B
| BNEQ_1B
| BNEQ_2B
| BNEQ_4B
| BLTINT_1B
| BLTINT_2B
| BLTINT_4B
| BLEINT_1B
| BLEINT_2B
| BLEINT_4B
| BGTINT_1B
| BGTINT_2B
| BGTINT_4B
| BGEINT_1B
| BGEINT_2B
| BGEINT_4B
| ULTINT
| UGEINT
| BULTINT_1B
| BULTINT_2B
| BULTINT_4B
| BUGEINT_1B
| BUGEINT_2B
| BUGEINT_4B
| GETPUBMET
| GETDYNMET
| STOP

val all                : t list
    
val push_retaddr       : t * t * t
val closure            : t * t * t
val closurerec         : t * t * t
val makeblock          : t * t
val branch             : t * t * t
val branchif           : t * t * t
val branchifnot        : t * t * t
val switch             : t * t * t
val pushtrap           : t * t * t
val constint           : t * t * t
val pushconstint       : t * t * t
val offsetint          : t * t * t
val offsetref          : t * t * t
val beq                : t * t * t
val bneq               : t * t * t
val bltint             : t * t * t
val bleint             : t * t * t
val bgtint             : t * t * t
val bgeint             : t * t * t
val bultint            : t * t * t
val bugeint            : t * t * t

val to_string : t -> string
