#ifndef _PINGROUPS_MZ_H
#define _PINGROUPS_MZ_H

#define _PPS_RPD2       (0 + _PPS_SET_A)
#define _PPS_RPG8       (1 + _PPS_SET_A)
#define _PPS_RPF4       (2 + _PPS_SET_A)
#define _PPS_RPD10      (3 + _PPS_SET_A)
#define _PPS_RPF1       (4 + _PPS_SET_A)
#define _PPS_RPB9       (5 + _PPS_SET_A)
#define _PPS_RPB10      (6 + _PPS_SET_A)
#define _PPS_RPC14      (7 + _PPS_SET_A)
#define _PPS_RPB5       (8 + _PPS_SET_A)
//#define   _PPS_RPXX       (9 + _PPS_SET_A)
#define _PPS_RPC1       (10 + _PPS_SET_A)
#define _PPS_RPD14      (11 + _PPS_SET_A)
#define _PPS_RPG1       (12 + _PPS_SET_A)
#define _PPS_RPA14      (13 + _PPS_SET_A)
#define _PPS_RPD6       (14 + _PPS_SET_A)
//#define   _PPS_RPXX       (15 + _PPS_SET_A)

#define _PPS_RPD3       (0 + _PPS_SET_B)
#define _PPS_RPG7       (1 + _PPS_SET_B)
#define _PPS_RPF5       (2 + _PPS_SET_B)
#define _PPS_RPD11      (3 + _PPS_SET_B)
#define _PPS_RPF0       (4 + _PPS_SET_B)
#define _PPS_RPB1       (5 + _PPS_SET_B)
#define _PPS_RPE5       (6 + _PPS_SET_B)
#define _PPS_RPC13      (7 + _PPS_SET_B)
#define _PPS_RPB3       (8 + _PPS_SET_B)
//#define   _PPS_RPXX       (9 + _PPS_SET_B)
#define _PPS_RPC4       (10 + _PPS_SET_B)
#define _PPS_RPD15      (11 + _PPS_SET_B)
#define _PPS_RPG0       (12 + _PPS_SET_B)
#define _PPS_RPA15      (13 + _PPS_SET_B)
#define _PPS_RPD7       (14 + _PPS_SET_B)
//#define   _PPS_RPXX       (15 + _PPS_SET_B)

#define _PPS_RPD9       (0 + _PPS_SET_C)
#define _PPS_RPG6       (1 + _PPS_SET_C)
#define _PPS_RPB8       (2 + _PPS_SET_C)
#define _PPS_RPB15      (3 + _PPS_SET_C)
#define _PPS_RPD4       (4 + _PPS_SET_C)
#define _PPS_RPB0       (5 + _PPS_SET_C)
#define _PPS_RPE3       (6 + _PPS_SET_C)
#define _PPS_RPB7       (7 + _PPS_SET_C)
//#define   _PPS_RPXX       (8 + _PPS_SET_C)
#define _PPS_RPF12      (9 + _PPS_SET_C)
#define _PPS_RPD12      (10 + _PPS_SET_C)
#define _PPS_RPF8       (11 + _PPS_SET_C)
#define _PPS_RPC3       (12 + _PPS_SET_C)
#define _PPS_RPE9       (13 + _PPS_SET_C)
//#define   _PPS_RPXX       (14 + _PPS_SET_C)
//#define   _PPS_RPXX       (15 + _PPS_SET_C)

#define _PPS_RPD1       (0 + _PPS_SET_D)
#define _PPS_RPG9       (1 + _PPS_SET_D)
#define _PPS_RPB14      (2 + _PPS_SET_D)
#define _PPS_RPD0       (3 + _PPS_SET_D)
//#define   _PPS_RPXX       (4 + _PPS_SET_D)
#define _PPS_RPB6       (5 + _PPS_SET_D)
#define _PPS_RPD5       (6 + _PPS_SET_D)
#define _PPS_RPB2       (7 + _PPS_SET_D)
#define _PPS_RPF3       (8 + _PPS_SET_D)
#define _PPS_RPF13      (9 + _PPS_SET_D)
//#define   _PPS_RPXX       (10 + _PPS_SET_D)
#define _PPS_RPF2       (11 + _PPS_SET_D)
#define _PPS_RPC2       (12 + _PPS_SET_D)
#define _PPS_RPE8       (13 + _PPS_SET_D)
//#define   _PPS_RPXX       (14 + _PPS_SET_D)
//#define   _PPS_RPXX       (15 + _PPS_SET_D)



#endif
